import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

export default function Home() {
  return (
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="deScription" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      {/* Nucleo Icons  */}
   {/* Material Icons  */}
   {/* CSS Files  */}
  <link rel="apple-touch-icon" sizes="76x76" href="/super-admin/img/apple-icon.png"/>
  <link rel="icon" type="image/png" href="/super-admin/img/favicon.png"/>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>

      </Head>
   <Script src="sci.js"></Script>
      <body className="g-sidenav-show  bg-gray-300" style={{backgroundImage: 'url(/super-admin/img/back.jpg)' ,   backgroundRepeat: 'no-repeat', backgroundSize: 'cover'}}>
  <div className="container-fluid" style={{width:'700px'}}>
    <div className="row" style={{marginTop:'100px'}}>
        <div className="col-xl-6 mb-xl-0 mb-4">
            <div className="card" style={{height:'100px'}}>
                <Link href="/super-admin/Sign-in"  target="_blank" rel="noreferrer"><a>
            <div className="card-header p-3 pt-2">
              
            <div className="icon icon-lg icon-shape bg-gradient-success shadow-success text-center border-radius-xl mt-n4 position-absolute">
                  <i className="material-icons opacity-10">person</i>
            </div>
                <div className="text-end pt-1">
                  <p className="text-sm mb-0 text-capitalize"></p>
                  <h4 className="mb-0">Super Admin Panel</h4>
                </div>
              </div>
             
              <hr className="dark horizontal my-0"/>
              <div className="card-footer p-3">
              </div>
            
            </a></Link>
      </div>  
      </div>   
                    
       
        <div className="col-xl-6 mb-xl-0 mb-4">
            <div className="card" style={{height:'100px'}}>
              <Link href="/ca-admin/sign-in" target="_blank" rel="noreferrer"><a>
              <div className="card-header p-3 pt-2">
              <div className="icon icon-lg icon-shape bg-gradient-info shadow-info text-center border-radius-xl mt-n4 position-absolute">
                  <i className="material-icons opacity-10">person</i>
                </div>
                <div className="text-end pt-1">
                  <p className="text-sm mb-0 text-capitalize"></p>
                  <h4 className="mb-0">CA Admin Panel</h4>
                </div>
              </div>
              <hr className="dark horizontal my-0"/>
              <div className="card-footer p-3">
              </div>
              </a></Link>
            </div>
        </div>
        <div className="col-xl-6 mb-xl-0 mb-4 my-4">
          <div className="card" style={{height:'100px'}}>
          <Link href="/staff-admin/Dashboard" target="_blank" rel="noreferrer"><a>

            <div className="card-header p-3 pt-2">
              <div className="icon icon-lg icon-shape bg-gradient-info shadow-info text-center border-radius-xl mt-n4 position-absolute">
                <i className="material-icons opacity-10">person</i>
              </div>
              <div className="text-end pt-1">
                <p className="text-sm mb-0 text-capitalize"></p>
                <h4 className="mb-0">Staff Admin Panel</h4>
              </div>
            </div>
            <hr className="dark horizontal my-0"/>
            <div className="card-footer p-3">
            </div>
            </a></Link>
          </div>
        </div>
        <div className="col-xl-6 mb-xl-0 mb-4 my-4">
            <div className="card" style={{height:'100px'}}>
              <div className="card-header p-3 pt-2">
                <div className="icon icon-lg icon-shape bg-gradient-warning shadow-warning text-center border-radius-xl mt-n4 position-absolute">
                  <i className="material-icons opacity-10">person</i>
                </div>
                <div className="text-end pt-1">
                  <p className="text-sm mb-0 text-capitalize"></p>
                  <h4 className="mb-0">Clients Admin Panel</h4>
                </div>
              </div>
              <hr className="dark horizontal my-0"/>
              <div className="card-footer p-3">
              </div>
            </div>
        </div>
      </div>
      </div>
      
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></Script>
      <Script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></Script>
  <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></Script>
  <Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></Script>
  <Script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></Script>
  <Script src="ccor.js"></Script>
</body>
</>
    
  )
}
